### ISSUE TITLE
Assests webm when exported corrupt

### ISSUE THREAD

**Issue by streamkiller** [CommunityDragon/Data#31]
Dear CDragon team,

I don't know if my question here is in the right place but you are my only hope ^^
I wanted to use some .webm animations for social media, but everytime i download .webm they get corrupted when played outside a HMTL5 webplayer.
For example if open "open_cm_promotion_outro.webm](https://raw.communitydragon.org/14.7/plugins/rcp-fe-lol-loot/global/default/assets/videos/open_cm_promotion_outro.webm)" in edge/chrome it works fine. Also if you download the file and upload it to discord. The discord placeholder image displays as corrupt but when clicking play it acts normal.
I tried using FFMPEG to decode and convert the video with different codec methods webm supports but to no luck. 
After that i installed obsidian to see if i extracted the webm myself from installed game it would be better, also no luck.
I have looked for other sources of league of legends client animations but there are none i could find. 

I hope to hear your thoughts on this, i have been stuck on this issue over 2 days now xD

Kind regards,
Dennis

**Comment by bangingheads** [comment]
It's not corrupted, you are just seeing the luma and color planes. The transparency created from the alpha channel is what these are missing since there's no pixels to blend with in a regular video player or the preview generated image.

You could use ffmpeg to get the premultiplied result which is what a browser would show which should allow you to have correct previews.
``ffmpeg -c:v libvpx -i open_cm_promotion_outro.webm -vf premultiply=inplace=1 output.webm``

**Comment by streamkiller** [comment]
Bro, you are a life saver! Thank you so so much! Is there anywhere I can send you a PayPal tip or something? <3
